name: Tests
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch'
        required: true
        default: 'master'
        type: choice
        options:
          - master
          - next-version
  schedule:
    - cron: '* * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |-
          echo "${{ github.event.inputs.branch || 'option' }}"
          echo "${{ github.ref }}"