name: Tests
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: false
        description: branch
        default: master
  schedule:
    - cron: '* * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |-
          echo hello
#          echo "${{ github.event.inputs.branch }}"
